# Generated by Django 5.2.3 on 2025-06-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='applied_at',
        ),
    ]
