# Generated by Django 5.2.3 on 2025-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0003_rename_applied_on_application_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
