# Generated by Django 5.2.3 on 2025-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0004_remove_jobpost_deadline_remove_jobpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Date and time for scheduled interview (admin set)', null=True),
        ),
    ]
